# Generated by Django 5.2.1 on 2025-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='فایل رزومه')),
                ('work_experience', models.TextField(blank=True, null=True, verbose_name='سابقه کاری (در صورت نداشتن فایل)')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
        ),
    ]
