# Generated by Django 5.2 on 2025-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='manager_note',
            field=models.TextField(blank=True, null=True, verbose_name='پیام مدیر (مثلاً تاریخ مصاحبه)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
    ]
